# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
  - id: hlint
    name: hlint
    description: HLint is a tool for suggesting possible improvements to Haskell code.
    entry: hlint src test app
    language: system
    files: '\.l?hs$'
  - id: fourmolu
    name: fourmolu
    description: Fourmolu is a formatter for Haskell source code
    entry: fourmolu --mode check src test app
    language: system
    files: '\.l?hs$'
